[package]
name = "domains"
version = "0.1.0"
authors = ["asteryx <asteryx82@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
listenfd = "0.3"
tera = "0.11"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"